{{- if and .Values.configmap (not (empty .Values.configmap.data)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ include "fullnamespace" . }}
data: {{- toYaml .Values.configmap.data | nindent 2 }}
{{- end }}