{{- if eq .Values.kind "StatefulSet"}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-headless
  namespace: {{ include "fullnamespace" . }}
  labels: {{- include "custom.appValues" .Values.appLabels | nindent 4 }}
    name: {{ include "fullname" . }}
spec:
  ports:
    {{- range .Values.service}}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .portName | trunc 63 }}
    {{- end }}
  selector: {{- include "custom.appValues" .Values.appLabels | nindent 4 }}
    name: {{ include "fullname" . }}
  clusterIP: None
{{- end }}