{{- if .Values.autoscaling }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ include "fullnamespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.kind | default "Deployment" }}
    name: {{ include "fullname" . }}
  minReplicas: {{ .Values.autoscaling.min }}
  maxReplicas: {{ .Values.autoscaling.max }}
  metrics:
  {{- range .Values.autoscaling.metrics }}
    - type: {{ .type }}
      {{- if eq .type "Resource" }}
      resource:
        name: {{ .resource.name }}
      {{- end }}
      {{- if eq .type "ContainerResource" }}
      containerResource:
        container: {{ .containerResource.container }}
        name: {{ .containerResource.name }}
      {{- end }}
      {{- if eq .type "Pods" }}
      pods:
      {{- end }}
      {{- if eq .type "Object" }}
      object:
        describedObject:
          apiVersion: {{ .object.describedObject.apiVersion }}
          kind: {{ .object.describedObject.kind }}
          name: {{ .object.describedObject.name }}
      {{- end }}
      {{- if eq .type "External" }}
      external:
      {{- end }}
        {{- if or (eq .type "Pods") (eq .type "Object") (eq .type "External") }}
        metric:
          name: {{ .metric.name }}
          {{- if .metric.selector }}
          selector:
            {{- if .metric.selector.matchLabels }}
            matchLabels: {{- toYaml .metric.selector.matchLabels | nindent 14 }}
            {{- end }}
            {{- if .metric.selector.matchExpressions }}
            matchExpressions: {{- toYaml .metric.selector.matchExpressions | nindent 14 }}
            {{- end }}
          {{- end }}
        target:
          type: {{ .target.type }}
          {{- if eq .target.type "Utilization" }}
          averageUtilization: {{ .target.averageUtilization }}
          {{- else if eq .target.type "AverageValue" }}
          averageValue: {{ .target.averageValue }}
          {{- else if eq .target.type "Value" }}
          value: {{ .target.value }}
          {{- end }}
      {{- end }}
  {{- end }}
  {{- if .Values.autoscaling.behavior }}
  behavior:
    {{- if .Values.autoscaling.behavior.scaleUp }}
    scaleUp:
      {{- if .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      {{- end }}
      {{- if .Values.autoscaling.behavior.scaleUp.selectPolicy }}
      selectPolicy: {{ .Values.autoscaling.behavior.scaleUp.selectPolicy }}
      {{- end }}
      policies:
      {{- range .Values.autoscaling.behavior.scaleUp.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
      {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.behavior.scaleDown }}
    scaleDown:
      {{- if .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      {{- end }}
      {{- if .Values.autoscaling.behavior.scaleDown.selectPolicy }}
      selectPolicy: {{ .Values.autoscaling.behavior.scaleDown.selectPolicy }}
      {{- end }}
      policies:
      {{- range .Values.autoscaling.behavior.scaleDown.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}