{{- if .Values.istioAuthorizationPolicy }}
{{- range .Values.istioAuthorizationPolicy.policies }}
---
apiVersion: {{ .istioApiVersion }}
kind: AuthorizationPolicy
metadata:
 name: {{ .name | trunc 63 }}
 namespace: {{ include "fullnamespace" $ }}
spec:
  action: {{ .action }}
  rules:
  {{- range .rules }}
  {{- if .from }}
  - from:
    {{- range .from }}
    - source: {{ .source | toYaml | nindent 8 }}
    {{- end }}
  {{- end }}
    {{- if .to }}
    to:
      {{- range .to }}
      - operation: {{ .operation | toYaml | nindent 10 }}
      {{- end }}
    {{- end }}
    {{- if .when }}
    when: {{ .when | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels: {{ .selectorMatchLabels | toYaml | nindent 6 }}
{{- end }}
{{- end }}