{{- if .Values.istioGateway }}
apiVersion: {{ .Values.istioGateway.istioApiVersion }}
kind: Gateway
metadata:
  name: {{ include "fullname" . }}
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    {{- range .Values.istioGateway.servers }}
    - hosts: {{ .hosts | toYaml | nindent 8 }}
      port:
        name: {{ .portName | trunc 63 }}
        number: {{ .portNumber }}
        protocol: {{ .portProtocol }}
      {{- if .tls }}
      tls: {{ .tls | toYaml | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}