{{- if .Values.istioRequestAuthentication }}
apiVersion: {{ .Values.istioRequestAuthentication.istioApiVersion }}
kind: RequestAuthentication
metadata:
  name: {{ include "fullname" . }}
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules: {{- toYaml .Values.istioRequestAuthentication.jwtRules | nindent 4 }}
{{- end }}