{{- if .Values.istioVirtualService }}
apiVersion: {{ .Values.istioVirtualService.istioApiVersion }}
kind: VirtualService
metadata:
    name: {{ include "fullname" . }}
    namespace: {{ include "fullnamespace" . }}
spec:
    gateways: {{- toYaml .Values.istioVirtualService.gateways | nindent 4 }}
    hosts: {{- toYaml .Values.istioVirtualService.istioHosts | nindent 4 }}
    {{- if .Values.istioVirtualService.http }}
    http: {{- toYaml .Values.istioVirtualService.http | nindent 4 }}
    {{- end }}
    {{- if .Values.istioVirtualService.tcp }}
    tcp: {{- toYaml .Values.istioVirtualService.tcp | nindent 4 }}
    {{- end }}
{{- end }}