{{- if .Values.secrets }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | trunc 63 }}
  namespace: {{ $.Values.namespace }}
type: {{ .type }}
data:
{{- if eq .type "kubernetes.io/dockerconfigjson" }}
  .dockerconfigjson: {{ .dockerconfigjson }}
{{- else if eq .type "kubernetes.io/tls" }}
  tls.crt: {{ .tls.crt }}
  tls.key: {{ .tls.key }}
{{- else if eq .type "kubernetes.io/dockercfg" }}
  .dockercfg: {{ .dockercfg }}
{{- else if eq .type "kubernetes.io/ssh-auth" }}
  ssh-privatekey: {{ .sshPrivatekey }}
{{- else if eq .type "Opaque" }}
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
