{{- if and .Values.secret (hasKey .Values.secret "data") (not (empty .Values.secret.data)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ include "fullnamespace" . }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
